export const GET_DOGS = 'GET_DOGS'
export const GET_DOGS_API = 'GET_DOGS_API'
export const GET_DOGS_DB = 'GET_DOGS_DB'
export const GET_ID = 'GET_ID'
export const GET_NAME = 'GET_NAME'
export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'
export const CREATE_DOG = 'CREATE_DOG'
export const FILTER_TEMP = 'FILTER_TEMP'